In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_wine
from sklearn.ensemble import RandomForestClassifier
from sklearn import model_selection
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.gridspec as gridspec
import tensorflow as tf
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

C:\Users\uditi\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
#loading dataset
wine = load_wine()
X = wine.data
Y = wine.target

In [3]:
data = pd.DataFrame(X)
print(wine.feature_names)
data.columns = wine.feature_names
data['target'] = Y
data['class'] = Y
print(data.shape)
data.describe()

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
(178, 15)


alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  178.000000  178.000000  178.000000         178.000000  178.000000   
mean    13.000618    2.336348    2.366517          19.494944   99.741573   
std      0.811827    1.117146    0.274344           3.339564   14.282484   
min     11.030000    0.740000    1.360000          10.600000   70.000000   
25%     12.362500    1.602500    2.210000          17.200000   88.000000   
50%     13.050000    1.865000    2.360000          19.500000   98.000000   
75%     13.677500    3.082500    2.557500          21.500000  107.000000   
max     14.830000    5.800000    3.230000          30.000000  162.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.742500    1.205000              0.270000         1.250000   
50%         2.355000    2.135000              0.340000         1.555000   
75%         2.800000    2.875000              0.437500         1.950000   
max         3.880000    5.080000              0.660000         3.580000   

       color_intensity         hue  od280/od315_of_diluted_wines      proline  \
count       178.000000  178.000000                    178.000000   178.000000   
mean          5.058090    0.957449                      2.611685   746.893258   
std           2.318286    0.228572                      0.709990   314.907474   
min           1.280000    0.480000                      1.270000   278.000000   
25%           3.220000    0.782500                      1.937500   500.500000   
50%           4.690000    0.965000                      2.780000   673.500000   
75%           6.200000    1.120000                      3.170000   985.000000   
max          13.000000    1.710000                      4.000000  1680.000000   

           target       class  
count  178.000000  178.000000  
mean     0.938202    0.938202  
std      0.775035    0.775035  
min      0.000000    0.000000  
25%      0.000000    0.000000  
50%      1.000000    1.000000  
75%      2.000000    2.000000  
max      2.000000    2.000000

In [4]:
le = LabelEncoder()
Y = le.fit_transform(Y)

In [5]:
Y_ohe = np.reshape(Y,(len(Y),1))
enc = OneHotEncoder()
Y_ohe = enc.fit_transform(Y_ohe).toarray()

In [6]:
print(Y_ohe) # one-hot-encoded data

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [7]:
x_train,x_test,y_train,y_test = model_selection.train_test_split(X,Y_ohe)

In [8]:
# weights & biases
n_input = 13
n_hidden_1 = 16
n_hidden_2 = 8
n_classes = 3

weights = {
    'h1': tf.Variable(tf.random_normal([n_input, n_hidden_1])),
    'h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_hidden_2, n_classes]))
}

biases = {
    'h1': tf.Variable(tf.random_normal([n_hidden_1])),
    'h2': tf.Variable(tf.random_normal([n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_classes]))
}


In [9]:
tf.trainable_variables()

[<tf.Variable 'Variable:0' shape=(13, 16) dtype=float32_ref>,
 <tf.Variable 'Variable_1:0' shape=(16, 8) dtype=float32_ref>,
 <tf.Variable 'Variable_2:0' shape=(8, 3) dtype=float32_ref>,
 <tf.Variable 'Variable_3:0' shape=(16,) dtype=float32_ref>,
 <tf.Variable 'Variable_4:0' shape=(8,) dtype=float32_ref>,
 <tf.Variable 'Variable_5:0' shape=(3,) dtype=float32_ref>]

In [10]:
def forward_propagation(x, weights, biases):
    in_layer1 = tf.add(tf.matmul(x, weights['h1']), biases['h1'])
    out_layer1 = tf.nn.relu(in_layer1)
    
    in_layer2 = tf.add(tf.matmul(out_layer1, weights['h2']), biases['h2'])
    out_layer2 = tf.nn.relu(in_layer2)
    
    output = tf.add(tf.matmul(out_layer2, weights['out']), biases['out'])
    return output

In [11]:
x = tf.placeholder("float", [None, n_input])
y = tf.placeholder(tf.int32, [None, n_classes])
pred = forward_propagation(x, weights, biases)

In [12]:
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=pred, labels = y))

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.



In [13]:
optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
optimize = optimizer.minimize(cost)

In [14]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [15]:
for i in range(400):
    total_cost, _ = sess.run([cost,optimize], feed_dict={x:X , y:Y_ohe})
    print(total_cost)

2158.116
1953.6259
1751.2267
1550.8126
1352.5277
1156.3444
963.642
775.0457
590.6835
413.10635
245.91386
262.015
367.04465
428.0822
456.11435
459.15433
442.19348
408.45453
359.83948
298.31885
225.11328
140.8727
69.410324
67.260605
96.210556
118.14897
126.34625
120.25902
102.027016
73.999664
40.00199
26.712038
66.137695
88.74092
84.96435
58.720203
29.324175
27.370087
39.131924
47.070423
46.381237
37.78095
24.819525
14.564144
12.360349
17.004478
24.547983
25.779634
20.553288
16.493553
15.843816
17.197727
18.821873
19.887505
19.702679
18.162834
15.617275
12.872952
11.507161
11.774977
13.244779
14.407668
14.564068
13.695275
12.4379225
11.768358
11.679211
11.987608
12.390124
12.330786
11.731001
11.030294
10.599646
10.4661
10.62584
10.89917
11.034864
10.825829
10.470606
10.205997
10.114531
10.093192
10.075726
10.006351
9.857957
9.675368
9.542057
9.493813
9.480995
9.46391
9.408181
9.288439
9.134505
8.99992
8.896316
8.827617
8.768684
8.703856
8.615711
8.501675
8.37843
8.265545
8.179737
8.10752

In [16]:
predictions = tf.argmax(pred, 1)
correct_labels = tf.argmax(y_test, 1)
correct_predictions = tf.equal(predictions, correct_labels)
predictions,correct_predictions  = sess.run([predictions, correct_predictions], feed_dict={x:x_test,y:y_test})
correct_predictions.sum()

36

In [17]:
score = correct_predictions.sum()/len(y_test)
score

0.8